name: outerboxkitchen
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  flutter_bloc: ^4.0.0
  equatable: ^1.1.0
  cached_network_image: ^2.3.1
  awesome_dialog: ^1.3.1
  audioplayers: ^0.17.3
  web_socket_channel: ^1.2.0
  flutter_pusher: ^1.0.2
  auto_size_text: ^2.1.0
  firebase_database: ^6.0.0
  firebase_messaging: ^5.0.3
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  firebase_storage: ^7.0.0
  path_provider: ^1.6.22
  path: ^1.8.0
  #  Database
  #  moor_flutter: ^3.1.0
  provider: ^4.3.3
  sqflite: ^1.3.2+4

  #  Printing
  bluetooth_thermal_printer: ^0.0.4
  esc_pos_utils: 0.4.7
  bluetooth_enable: ^0.1.1
  flutter_blue: ^0.7.3
  blue_thermal_printer: ^1.1.3

  intl: ^0.16.1
  timer_builder: ^1.3.0
  uuid: ^2.0.4
  image: ^2.1.4
  loading_indicator: ^2.0.1
  device_info: ^2.0.0
  flutter_svg: 0.19.3

  #chat and bulletin libraries
  stream_chat_flutter: ^0.2.20+3
  rxdart: ^0.24.0
  http_parser: ^3.1.4
  multi_image_picker: ^4.6.1
  carousel_pro: ^1.0.0
  flutter_callkeep: ^0.1.8
  flutter_local_notifications: ^1.4.4+4
  overlay_support: ^1.0.5
  timeago: ^2.0.29
  flutter_chat_bubble: ^1.0.2
  comment_tree: ^0.1.2
  readmore: ^2.0.0
  permission_handler: ^5.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/mp3/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
